In [1]:
import HophildNet as hn
import pandas as pd
import image
import numpy as np
from Hopfield_parser import convert_from, convert_to, parse_data, reparse_data

In [2]:
atribute_data = pd.read_csv('atributes.csv')

In [3]:
test_verb = np.array([1, 1, 1, 1, 1])

In [4]:
atribute_data.head()

name  a1  a2  a3  a4  a5
0   v5   1   0   1   1   0
1   v6   0   1   0   0   0
2   v7   1   0   1   0   0

In [5]:
data = atribute_data[atribute_data.columns[1:]]
data

a1  a2  a3  a4  a5
0   1   0   1   1   0
1   0   1   0   0   0
2   1   0   1   0   0

In [6]:
data.shape[1]

5

In [7]:
hopfield_data = convert_to(data.values)
hopfield_data

array([[ 1, -1,  1,  1, -1],
       [-1,  1, -1, -1, -1],
       [ 1, -1,  1, -1, -1]])

In [8]:
net = hn.HopfieldNet(hopfield_data.shape[1])

In [9]:
for verb in hopfield_data:
    net.teach(verb)

In [10]:
net.stop_teach()
net.set_threshold(0)

In [11]:
result_verb = convert_from(net.forward(convert_to(test_verb))[0])
result_verb = result_verb.astype(np.int64)
result_verb

array([1, 0, 1, 1, 0])

In [12]:
data.values

array([[1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0]])

In [13]:
i = 0
while i < data.shape[0]:
    if (np.array_equal(data.values[i], result_verb)):
        break
    i += 1
str_num = i

In [14]:
if i == data.shape[0]:
    print('Новая вершина')
    str_num = -1
else:
    print('Новая вершина должна быть объединена с вершиной ',atribute_data['name'][str_num],' (', str_num, ')')
str_num

Новая вершина должна быть объединена с вершиной  v5  ( 0 )


0